server:
  port: 8092

  
spring:
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/autherization?createDatabaseIfNotExist=true
    username: root
    password: 
    hikari:
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      maximum-pool-size: 5
      minimum-idle: 5
    
    
  jpa:
    hibernate:
      ddl-auto: create